### ISSUE TITLE
Is this storage backend maintained?

### ISSUE THREAD

**Issue by hairmare** [thumbor-community/mongodb#3]
Thanks for publishing this! 

I noticed that there are some PRs open that haven't gotten any feedback and would like to inquire if this storage backend is still maintained? 

@masom You don't seem to be watching this repo anymore, any chance you could give us a quick update (as all of the commits in the repo belong to you)?

**Comment by masom** [comment]
> I noticed that there are some PRs open that haven't gotten any feedback and would like to inquire if this storage backend is still maintained?

This backend isn't actively being worked on and I don't watch all thumbor-community repositories.

The two open PRs weren't requesting any reviewers. One of them adds support for Python3 which wasn't supported by Thumbor itself.

The other PR is not mergeable in its current state as it contains a high number of commits and removes configurable values, with no tests. I'm not even sure why it's opened as a PR because it contains some environment-specific operations.

Other than that, contributions are welcome and if someone wants to actively maintain this project they could get commit access after opening good PRs.

**Comment by hairmare** [comment]
@masom Thank you very much for your reassuring feedback!
